-- Preserva também os metadados da empresa presentes no seed.
CREATE TABLE IF NOT EXISTS companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS surveys (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('NPS', 'CSAT')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    email TEXT NOT NULL CHECK (length(trim(email)) > 0),
    segment TEXT,
    deleted_at TIMESTAMPTZ
);

-- Um e-mail só pode pertencer a um contato ativo, ignorando maiúsculas.
-- Após a exclusão lógica, o mesmo e-mail pode ser cadastrado novamente.
CREATE UNIQUE INDEX IF NOT EXISTS ux_contacts_active_email
    ON contacts (lower(email))
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS responses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id INTEGER NOT NULL REFERENCES surveys (id),
    contact_id INTEGER NOT NULL REFERENCES contacts (id),
    score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 10),
    comment TEXT,
    channel TEXT NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

-- Facilita buscar o histórico válido de um contato, mais recente primeiro.
CREATE INDEX IF NOT EXISTS ix_responses_active_contact_date
    ON responses (contact_id, responded_at DESC)
    WHERE deleted_at IS NULL;
